### ISSUE TITLE
Toffoli with Tequila

### ISSUE THREAD

**Issue by SolidTux** [Mc-Zen/quill#12]
Currently, it seems like there is no way to construct a Toffoli (or any other gate with multiple controls for that matter).

**Comment by Mc-Zen** [comment]
Hi @SolidTux ,

that's right - at least with Tequila - this is currently not possible. With the "normal" usage, it should work however. 
I will look into that!

**Comment by SolidTux** [comment]
Yes, the normal use works flawless. Thanks a lot for the package!

**Comment by SolidTux** [comment]
I think it's enough to have it like this. Maybe it would make sense to expose the functionality, so people can define their own gates with more controls, but I'm not sure about predefined gates.

I'm not too deep into this topic, so I don't know if people actually use these in more complex programs, but realistically already CCX is hard enough to realize in hardware.

**Comment by Mc-Zen** [comment]
Okay! Thanks for reporting this issue

**Comment by Mc-Zen** [comment]
@SolidTux, this is now available with quill:0.5.0.
