### ISSUE TITLE
make midstick behavior similar to lstick and rstick

### ISSUE THREAD

**Issue by maxtremblay** [Mc-Zen/quill#2]
Hello, thanks for this great package. 

I have some trouble with midstick and fill color. I have set the option 

```typst
#quantum-circuit(
    fill: accent-color,
    midstick($ket(Omega_1)$),
    mqgate($hat(U)(tau_1, hat(P)_1)$, n: 4),
    ...

)
```

As you can see, the labels from midstick are filled with a red background which I would prefer to avoid.

![screenshot_02282024_09_44_53](https://github.com/Mc-Zen/quill/assets/52462375/d51a3be1-3725-4c34-aac7-f1d6c885740c)

I can use lstick instead, but in that case, the kets and dots are not aligned.

![screenshot_02282024_09_49_11](https://github.com/Mc-Zen/quill/assets/52462375/20d7b797-7a49-4e65-b7c7-92153e16c3e2)

**Comment by Mc-Zen** [comment]
Also: in the (rather near) future, (when user-defined types are added to Typst), `gate` will become an "element". The `fill` parameter will then be deprecated for `quantum-circuit` and you can instead write
```typ
#set gate(fill: accent-color)
```
which is much more flexible. Just so you know

**Comment by maxtremblay** [comment]
Ok. Thank you for the solution. I will go with that for now :smile:
