### ISSUE TITLE
Gallery contains false information

### ISSUE THREAD

**Issue by EricQ01** [Mc-Zen/quill#5]
The gallery shows the typst instruction of the multi-qubit unitary gate as `mqgate($U$, 3)`. It should be `mqgate($U$, n : 3)`. The code below does not compile.

```
#import "@preview/quill:0.2.1": *

#quantum-circuit(
    lstick($|0〉$), mqgate($U$, 4), [\ ], 
    lstick($|0〉$), 1, [\ ],
    lstick($|0〉$), 1, [\ ],
    lstick($|0〉$), 1, [\ ],
)
```

**Comment by Mc-Zen** [comment]
Oh, that's right, thanks for reporting!
