### ISSUE TITLE
How to draw a circuit inside a canvas?

### ISSUE THREAD

**Issue by GiggleLiu** [Mc-Zen/quill#8]
Thank you for developing this package! I was hoping the following way of using this package works, however, an error occured. Is there a way to include a quantum circuit in another drawing as a sub-figure?

```typst
  #canvas({
  import draw: *
  // some plots

  quantum-circuit(
    1, ctrl(1), 1, [\ ],
    1, targ(), 1
  )
  })
```

**Comment by Mc-Zen** [comment]
Hi @GiggleLiu !

I'm not a cetz pro but this is easy I think. You need to put it into a cetz `content()`, just as you would do if you want to add some text etc. 

```typ

   #canvas({
      import draw: *
      // some plots
    
      content((0, 0), quantum-circuit(
        1, ctrl(1), 1, [\ ],
        1, targ(), 1
      ))
  })
```

This would place the circuit at the coordinates `(0, 0)`. 

I hope this helps!

**Comment by GiggleLiu** [comment]
Oh you are right, thank you!

**Comment by Mc-Zen** [comment]
You're welcome!
